<a href="https://colab.research.google.com/github/celestebgriff/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_422_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

In [0]:
##### Your Code Here #####

import numpy as np

X = np.array(([0,0,1],
              [0,1,1],
              [1,0,1],
              [0,1,0],
              [1,0,0],
              [1,1,1],
              [0,0,0]), dtype=float)

y = np.array(([0],
              [1],
              [1],
              [1],
              [1],
              [0],
              [0]), dtype=float)

In [0]:
class NeuralNetwork(): 
    
    def __init__(self, inputs, hiddens, outputs):
        # Setup Arch
        self.inputs = inputs
        self.hiddenNodes = hiddens
        self.outputNodes = outputs
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) 
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1-sx)
    
    def feed_forward(self, X):
        """Calculate the NN inference using feed forward."""
        self.hidden_sum = np.dot(X, self.weights1) 
        self.activated_hidden = self.sigmoid(self.hidden_sum) 
        self.output_sum = np.dot(self.activated_hidden, self.weights2) 
        self.activated_output = self.sigmoid(self.output_sum) 
        return self.activated_output
    
    def backward(self, X,y,o):
        """Back prop thru the network"""
        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(self.output_sum) 
        self.z2_error = self.o_delta.dot(self.weights2.T) 
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.hidden_sum) 
        self.weights1 += X.T.dot(self.z2_delta) 
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [3]:
nn = NeuralNetwork(3,4,1)

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.79186077]
 [0.82337926]
 [0.7577062 ]
 [0.77901018]
 [0.69734528]
 [0.79186902]
 [0.73559787]]
Loss: 
 0.28936311412081894
+---------EPOCH 2---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.73958904]
 [0.7665743 ]
 [0.70061769]
 [0.71963481]
 [0.64363365]
 [0.72985072]
 [0.68402521]]
Loss: 
 0.27104049402985597
+---------EPOCH 3---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.69173714]
 [0.71293345]
 [0.65168349]
 [0.66584773]
 [0.59935299]
 [0.67484237]
 [0.63840381]]
Loss: 
 0.2596256114520701
+---------EPOC

### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
 
model = Sequential([
    Dense(3, activation='sigmoid', input_dim=3),
    Dense(1, activation='sigmoid')
])
 
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])
 
results = model.fit(X,y, epochs=100)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 7 samples
Epoch 1/100
7/7 [==============================] - 0s 37ms/sample - loss: 0.6869 - acc: 0.5714
Epoch 2/100
7/7 [==============================] - 0s 233us/sample - loss: 0.6868 - acc: 0.5714
Epoch 3/100
7/7 [==============================] - 0s 194us/sample - loss: 0.6867 - acc: 0.5714
Epoch 4/100
7/7 [==============================] - 0s 244us/sample - loss: 0.6866 - acc: 0.5714
Epoch 5/100
7/7 [==============================] - 0s 220us/sample - loss: 0.6865 - acc: 0.5714
Epoch 6/100
7/7 [==============================] - 0s 212us/sample - loss: 0.6864 - acc: 0.5714
Epoch 7/100
7/7 [==============================] - 0s 165us/sample - loss: 0.6863 - acc: 0.5714
Epoch 8/100
7/7 [==============================] - 0s 214us/sample - loss: 0.6862 - acc: 0.5714
Epoch 9/100
7/7 [======================

## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [0]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [0]:
# input image dimensions
img_rows, img_cols = 28, 28

In [7]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [9]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [0]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [11]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [0]:
##### Your Code Here #####

class NeuralNetwork:
    
    def __init__(self, learning_rate):
        self.learning_rate = learning_rate
        
        # Set up architecture
        self.inputs = 784
        self.hiddenNodes = 500
        self.outputNodes = 1
        
        # Initialize weights
        # 784 x 500
        # Input to Hidden (1st set of weights)
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        self.weights1 = self.weights1 / self.weights1.shape[0]
        # 500 x 1
        # Hidden to Output (2nd set of weights)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        self.weights2 = self.weights2 / self.weights2.shape[0]
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1 - sx)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        # Weighted sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activate
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum of activated hidden
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """
        Backpropagation through the network
        """
        
        self.o_error = y - o  # Error in the output
        
        # Apply the derivative of sigmoid to error
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error: how much were our output layer weights off
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # z2 delta: how much were the weights off?
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        

        self.weights1 += self.learning_rate * np.reshape(X, (-1, 1)).dot(np.reshape(self.z2_delta, (-1, 1)).T)  # Adjust first set (input -> hidden) weights
        self.weights2 += self.learning_rate * np.reshape(self.activated_hidden, (-1, 1)).dot(np.reshape(self.o_delta, (-1, 1)).T)  # Adjust second set
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [13]:
# Train
learning_rate = 0.1
nn = NeuralNetwork(learning_rate)
epochs = 100
batch_size = 100

losses = []
for i in range(epochs):
    loss = 0
    for k in range(batch_size):
        col = np.random.randint(x_train.shape[0])
        input_vector = x_train[col, :]
        target_vector = y_train[col]
        nn.train(input_vector, target_vector)
        loss += np.linalg.norm(nn.sigmoid(np.dot(nn.weights2.T, nn.sigmoid(np.dot(nn.weights1.T,input_vector)))) - target_vector, 2)
    if (i+1) % 10 == 0:
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print("Loss: \n", str(loss/batch_size))
    losses.append(loss)

+---------EPOCH 10---------+
Loss: 
 0.12796736060480732
+---------EPOCH 20---------+
Loss: 
 0.017688724446443718
+---------EPOCH 30---------+
Loss: 
 0.031205534629761725
+---------EPOCH 40---------+
Loss: 
 0.023952085784331806
+---------EPOCH 50---------+
Loss: 
 0.015406288546752694
+---------EPOCH 60---------+
Loss: 
 0.021605269355553812
+---------EPOCH 70---------+
Loss: 
 0.007940435322135807
+---------EPOCH 80---------+
Loss: 
 0.020435150151828615
+---------EPOCH 90---------+
Loss: 
 0.009825444956692748
+---------EPOCH 100---------+
Loss: 
 0.005915820832226317


## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?